"""initial registry schema

Revision ID: c53e5d451f24
Revises:
Create Date: 2026-09-06 00:44:14.582172
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_setting",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "descriptor",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("package", sa.String(length=255), nullable=False),
        sa.Column("source_filename", sa.String(length=255), nullable=False),
        sa.Column("file_descriptor_set", sa.LargeBinary(), nullable=False),
        sa.Column("protoc_version", sa.String(length=32), nullable=True),
        sa.Column("imported_only", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("package"),
    )
    op.create_table(
        "server_group",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "message_type",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("descriptor_id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=511), nullable=False),
        sa.Column("field_names", sa.JSON(), nullable=False),
        sa.Column("field_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["descriptor_id"], ["descriptor.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("full_name", name="uq_message_type_full_name"),
    )
    op.create_table(
        "server",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=True),
        sa.Column("colour", sa.String(length=9), nullable=False),
        sa.Column("urls", sa.JSON(), nullable=False),
        sa.Column("auth_mode", sa.String(length=16), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("nkey_jwt_is_file", sa.Boolean(), nullable=False),
        sa.Column("creds_path", sa.Text(), nullable=True),
        sa.Column("tls_enabled", sa.Boolean(), nullable=False),
        sa.Column("tls_verify", sa.Boolean(), nullable=False),
        sa.Column("tls_ca_path", sa.Text(), nullable=True),
        sa.Column("tls_cert_path", sa.Text(), nullable=True),
        sa.Column("tls_key_path", sa.Text(), nullable=True),
        sa.Column("monitoring_url", sa.Text(), nullable=True),
        sa.Column("monitoring_poll_seconds", sa.Float(), nullable=False),
        sa.Column("system_account_enabled", sa.Boolean(), nullable=False),
        sa.Column("system_username", sa.String(length=255), nullable=True),
        sa.Column("system_creds_path", sa.Text(), nullable=True),
        sa.Column("client_name", sa.String(length=120), nullable=False),
        sa.Column("inbox_prefix", sa.String(length=64), nullable=False),
        sa.Column("jetstream_domain", sa.String(length=120), nullable=True),
        sa.Column("max_reconnect_attempts", sa.Integer(), nullable=False),
        sa.Column("connect_on_startup", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["group_id"], ["server_group.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "saved_filter",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("server_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("subject", sa.String(length=511), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["server_id"], ["server.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "server_secret",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("server_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("nonce", sa.LargeBinary(), nullable=False),
        sa.Column("key_version", sa.Integer(), nullable=False),
        sa.Column("hint", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["server_id"], ["server.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("server_id", "kind", name="uq_server_secret_kind"),
    )
    op.create_table(
        "subject_rule",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("server_id", sa.Uuid(), nullable=True),
        sa.Column("pattern", sa.String(length=511), nullable=False),
        sa.Column("type_full_name", sa.String(length=511), nullable=False),
        sa.Column("precedence", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["server_id"], ["server.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subject_rule")
    op.drop_table("server_secret")
    op.drop_table("saved_filter")
    op.drop_table("server")
    op.drop_table("message_type")
    op.drop_table("server_group")
    op.drop_table("descriptor")
    op.drop_table("app_setting")
    # ### end Alembic commands ###
