/** The typed HTTP client.
 *
 * Every request and response type here is read out of `api.d.ts`, which is
 * generated by `npm run types`. There is deliberately not one hand-written
 * response interface in the frontend: a backend struct that drifts from the UI
 * has to break `npm run build` rather than production.
 *
 * The socket (`lib/ws.ts`) is read-path only. Everything that changes something
 * -- subscribe, publish, purge, delete -- goes through here.
 */

import type { operations, paths } from "./api.d";

type Method = "get" | "post" | "put" | "patch" | "delete";

/** Paths that actually declare this method. `paths` lists all nine per entry
 * with the unused ones typed `never`, so this is what keeps autocomplete honest. */
type PathsWith<M extends Method> = {
  [P in keyof paths]: paths[P] extends { [K in M]: object } ? P : never;
}[keyof paths];

type Operation<P extends keyof paths, M extends Method> =
  paths[P] extends { [K in M]: infer O } ? O : never;

type JsonOf<T> = T extends { content: { "application/json": infer B } } ? B : never;

type ParamsOf<O> = O extends { parameters: infer Pr } ? Pr : never;
type PathParamsOf<O> = ParamsOf<O> extends { path?: infer X } ? Exclude<X, undefined> : never;
type QueryParamsOf<O> = ParamsOf<O> extends { query?: infer X } ? Exclude<X, undefined> : never;
type BodyOf<O> = O extends { requestBody?: infer R } ? JsonOf<NonNullable<R>> : never;

/** The 2xx body. 204 handlers have no `content`, which collapses to `never` and
 * is surfaced to callers as `void`. */
type ResultOf<O> = O extends { responses: infer R }
  ? R extends { 200: infer X }
    ? JsonOf<X>
    : R extends { 201: infer X }
      ? JsonOf<X>
      : void
  : void;

/** Litestar's error body, taken from any operation that declares a 400 rather
 * than written out by hand. Every 4xx and 5xx from the app has this shape. */
type Problem = {
  [K in keyof operations]: operations[K] extends {
    responses: { 400: { content: { "application/json": infer B } } };
  }
    ? B
    : never;
}[keyof operations];

type RequiredKeysOf<T> = Exclude<
  { [K in keyof T]: T extends Record<K, T[K]> ? K : never }[keyof T],
  undefined
>;

type Init<O> = {
  /** URL template holes, e.g. `{ server_id }`. */
  path?: PathParamsOf<O>;
  query?: QueryParamsOf<O>;
  body?: BodyOf<O>;
  signal?: AbortSignal;
  headers?: Record<string, string>;
};

/** `[init]` when the operation needs one, `[init?]` when it does not, so
 * `api.get("/api/health")` stays a one-liner while a path parameter cannot be
 * forgotten. */
type Args<O> = RequiredKeysOf<Init<O>> extends never ? [init?: Init<O>] : [init: Init<O>];

/** Both halves are served from one origin in production, and in dev Vite proxies
 * `/api` to the backend container. Either way the request is same-origin, so
 * there is no base URL to configure and no CORS preflight to pay for. */
const BASE = "";

/** A non-2xx response, with the backend's own `detail` string.
 *
 * `fix` is filled in for the cases where the API is telling us something a person
 * can act on; screens show it rather than the status code. */
export class ApiError extends Error {
  readonly status: number;
  readonly url: string;
  readonly problem: Problem | null;

  constructor(status: number, url: string, problem: Problem | null) {
    super(problem?.detail ?? `${status} from ${url}`);
    this.name = "ApiError";
    this.status = status;
    this.url = url;
    this.problem = problem;
  }
}

function buildUrl(
  template: string,
  path: Record<string, unknown> | undefined,
  query: Record<string, unknown> | undefined,
): string {
  let url: string = template;
  if (path) {
    for (const [key, value] of Object.entries(path)) {
      url = url.replace(`{${key}}`, encodeURIComponent(String(value)));
    }
  }
  if (query) {
    const search = new URLSearchParams();
    for (const [key, value] of Object.entries(query)) {
      if (value === undefined || value === null) continue;
      // Repeated key per item is what Litestar reads back as a sequence.
      if (Array.isArray(value)) for (const item of value) search.append(key, String(item));
      else search.append(key, String(value));
    }
    const qs = search.toString();
    if (qs) url += `?${qs}`;
  }
  return BASE + url;
}

async function request<P extends keyof paths, M extends Method>(
  method: M,
  template: P,
  init: Init<Operation<P, M>> | undefined,
): Promise<ResultOf<Operation<P, M>>> {
  const opts = (init ?? {}) as {
    path?: Record<string, unknown>;
    query?: Record<string, unknown>;
    body?: unknown;
    signal?: AbortSignal;
    headers?: Record<string, string>;
  };
  const url = buildUrl(template as string, opts.path, opts.query);
  const hasBody = opts.body !== undefined;
  // A file upload goes as multipart, and the browser must set Content-Type
  // itself so the boundary matches the body it generates. Setting it here would
  // produce a header the payload does not agree with.
  const isMultipart = hasBody && opts.body instanceof FormData;

  const response = await fetch(url, {
    method: method.toUpperCase(),
    headers: {
      Accept: "application/json",
      ...(hasBody && !isMultipart ? { "Content-Type": "application/json" } : {}),
      ...opts.headers,
    },
    ...(hasBody
      ? { body: isMultipart ? (opts.body as FormData) : JSON.stringify(opts.body) }
      : {}),
    ...(opts.signal ? { signal: opts.signal } : {}),
  });

  if (!response.ok) {
    // A proxy or a crash can answer with HTML; the error must survive that.
    let problem: Problem | null = null;
    try {
      problem = (await response.json()) as Problem;
    } catch {
      problem = null;
    }
    throw new ApiError(response.status, url, problem);
  }

  if (response.status === 204 || response.headers.get("Content-Length") === "0") {
    return undefined as ResultOf<Operation<P, M>>;
  }
  return (await response.json()) as ResultOf<Operation<P, M>>;
}

export const api = {
  get: <P extends PathsWith<"get">>(path: P, ...args: Args<Operation<P, "get">>) =>
    request("get", path, args[0]),
  post: <P extends PathsWith<"post">>(path: P, ...args: Args<Operation<P, "post">>) =>
    request("post", path, args[0]),
  put: <P extends PathsWith<"put">>(path: P, ...args: Args<Operation<P, "put">>) =>
    request("put", path, args[0]),
  patch: <P extends PathsWith<"patch">>(path: P, ...args: Args<Operation<P, "patch">>) =>
    request("patch", path, args[0]),
  delete: <P extends PathsWith<"delete">>(path: P, ...args: Args<Operation<P, "delete">>) =>
    request("delete", path, args[0]),
};

/** A react-query key that is the request itself.
 *
 * Two screens asking for the same path and parameters share a cache entry
 * without having to agree on a key by hand. */
export function apiKey(path: string, init?: { path?: unknown; query?: unknown }): unknown[] {
  return ["api", path, init?.path ?? null, init?.query ?? null];
}

/** The cache-key prefix for every read of a path, whatever its parameters.
 *
 * `invalidateQueries({ queryKey: apiPath("/api/schemas/rules") })` refreshes that
 * read for every server and every filter. Written by hand it was a silent
 * footgun: keys begin with `"api"`, and a prefix that omits it matches nothing
 * at all -- so the invalidation ran, succeeded, and refreshed no screen.
 */
export function apiPath(path: keyof paths): unknown[] {
  return ["api", path];
}

/** `useQuery(apiQuery("/api/servers/{server_id}", { path: { server_id } }))`.
 *
 * Wired to the same abort signal react-query already manages, so a screen that
 * unmounts mid-flight cancels rather than resolving into nothing. */
export function apiQuery<P extends PathsWith<"get">>(path: P, ...args: Args<Operation<P, "get">>) {
  const init = args[0] as Init<Operation<P, "get">> | undefined;
  return {
    queryKey: apiKey(path as string, init),
    queryFn: ({ signal }: { signal: AbortSignal }) =>
      request("get", path, { ...(init ?? {}), signal } as Init<Operation<P, "get">>),
  };
}

export type { paths, operations, Problem };
